### ISSUE TITLE
feature request: bring back the minimum PP please

### ISSUE THREAD

**Issue by TheCodeIsALie** [kinsi55/BeatSaber_BetterSongSearch#1]
First of all, thank you for this mod!!!
The minimum PP filter feature was awesome and I am missing it badly,
I will be glad if you bring it back <3

**Comment by kinsi55** [comment]
The issue with the min PP slider is that it is *very* connected to the star value of the song - Because that is what I use to calculate the PP value, so I got rid of it to unclutter the UI (Because I had to get rid of one of the sliders on the left). Most of the time you can guessimate a minimum star filter and use that. I will probably not bring back the seperate slider for it sorry!
