### ISSUE TITLE
Feature Request: Download All songs in given filter

### ISSUE THREAD

**Issue by raineio** [kinsi55/BeatSaber_BetterSongSearch#15]
One thing that is missing from More Songs/BeatSaverDownloader is the ability to download all songs, or batch download with specified songs.

Would be appreciated if you would be able to add this to BSS

**Comment by kinsi55** [comment]
You can create a Playlist based off your settings and download that with Playlist manager, or batch download (up to 30) multiple times. I didn't want people to just have bss download thousands of songs and just go afk which is why I setup this arbitrary limitation

That being said, the multi select thing isn't something I'll add - I don't see the advantage / need for it compared to just clicking download on the songs that you want

That being said, now that beatsaver uses r2cdn and downloads don't have any impact on it whatsoever I might increase the batch download limit to 100

**Comment by wolfcomp** [comment]
Could you have a checkbox for say everything in your search as it would make downloading all the ranked songs much easier than clicking multiple times.

**Comment by kinsi55** [comment]
Again, you can create a playlist in those cases and download that playlist with Playlist manager (You can add up to 5000 songs to a playlist at once)

**Comment by wolfcomp** [comment]
i dont want to have to get a playlist when i find out i want to download more songs while im in the game.

**Comment by kinsi55** [comment]
No what I meant is you can create a playlist _right in better song search_ and download that _in game_ with Playlist manager

**Comment by kinsi55** [comment]
My suggested change is now implemented - Batch download goes to 100 with a note / reference to the Playlist creation feature.
